-- =============================================================================
-- Migration 004 — Catálogo da cesta básica do DIEESE
--
-- GERADO por dados/gerar_catalogo_dieese.py a partir de cesta_agosto.csv.
-- Não edite à mão: altere o CSV ou o gerador e gere de novo.
--
-- Substitui o catálogo fictício de 002 (preços inventados) pelos preços
-- médios da Pesquisa Nacional da Cesta Básica do DIEESE, agosto de 2026.
-- O escopo é Juazeiro do Norte/CE:
--   * cada nome de cidade do CSV vira um supermercado FICTÍCIO dentro de
--     Juazeiro do Norte, com os preços DIEESE daquela cidade (28 no total);
--   * as localizações são fictícias: espiral determinística num raio de
--     6.0 km do centro, sem relação com os preços;
--   * os produtos são os 13 itens da cesta, e só eles;
--   * cada produto tem duas marcas FICTÍCIAS: a primeira custa o preço DIEESE
--     +8%, a segunda -8% (a média das duas é o preço publicado);
--   * célula "-" no CSV = produto indisponível naquela cidade (sem preço);
--   * a base não informa estoque: todo preço entra com 1000 unidades.
--   * sem nenhum preço na pesquisa (o supermercado existe, mas não
--     oferta nada): Macaé.
--
-- O catálogo anterior era todo fictício e é removido — junto com tudo que
-- dependia dele (itens de lista e recomendações). As contas de usuário são
-- preservadas. Sem BEGIN/COMMIT: o runner aplica cada arquivo numa transação.
-- =============================================================================

-- 1. Remove o catálogo fictício e o que dependia dele.
DELETE FROM recomendacoes;
DELETE FROM itens_lista;
DELETE FROM precos;
DELETE FROM marcas;
DELETE FROM produtos;
DELETE FROM mercados;
DELETE FROM listas_compra
 WHERE usuario_id IN (SELECT id FROM usuarios WHERE email = 'demo@exemplo.com');

COMMENT ON COLUMN mercados.latitude  IS 'Latitude em graus decimais (WGS84); usada no cálculo de distância em linha reta feito na aplicação.';
COMMENT ON COLUMN mercados.longitude IS 'Longitude em graus decimais (WGS84); usada no cálculo de distância em linha reta feito na aplicação.';

-- 2. Supermercados: um por nome de cidade do CSV, todos em Juazeiro do Norte.
INSERT INTO mercados (nome, latitude, longitude, endereco)
VALUES
    ('Supermercado Brasília', -7.213100, -39.308032, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Brasília/DF'),
    ('Supermercado Campo Grande', -7.204664, -39.324583, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Campo Grande/MS'),
    ('Supermercado Cuiabá', -7.229162, -39.313879, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Cuiabá/MT'),
    ('Supermercado Goiânia', -7.197960, -39.303600, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Goiânia/GO'),
    ('Supermercado Belo Horizonte', -7.216868, -39.336771, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Belo Horizonte/MG'),
    ('Supermercado Rio de Janeiro', -7.225936, -39.294961, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Rio de Janeiro/RJ'),
    ('Supermercado São Paulo', -7.187993, -39.322103, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de São Paulo/SP'),
    ('Supermercado Vitória', -7.237883, -39.328274, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Vitória/ES'),
    ('Supermercado Curitiba', -7.202901, -39.287151, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Curitiba/PR'),
    ('Supermercado Florianópolis', -7.201108, -39.344584, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Florianópolis/SC'),
    ('Supermercado Porto Alegre', -7.243028, -39.301183, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Porto Alegre/RS'),
    ('Supermercado Belém', -7.180104, -39.304868, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Belém/PA'),
    ('Supermercado Boa Vista', -7.231177, -39.346742, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Boa Vista/RR'),
    ('Supermercado Macapá', -7.221145, -39.278415, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Macapá/AP'),
    ('Supermercado Manaus', -7.181334, -39.337811, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Manaus/AM'),
    ('Supermercado Palmas', -7.252914, -39.320500, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Palmas/TO'),
    ('Supermercado Porto Velho', -7.186406, -39.283374, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Porto Velho/RO'),
    ('Supermercado Rio Branco', -7.211337, -39.358262, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Rio Branco/AC'),
    ('Supermercado Aracaju', -7.244038, -39.283962, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Aracaju/SE'),
    ('Supermercado Fortaleza', -7.168118, -39.317397, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Fortaleza/CE'),
    ('Supermercado João Pessoa', -7.248549, -39.345118, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de João Pessoa/PB'),
    ('Supermercado Maceió', -7.206795, -39.268065, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Maceió/AL'),
    ('Supermercado Natal', -7.185474, -39.355322, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Natal/RN'),
    ('Supermercado Recife', -7.261328, -39.304364, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Recife/PE'),
    ('Supermercado Salvador', -7.169306, -39.290005, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Salvador/BA'),
    ('Supermercado São Luís', -7.228751, -39.364749, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de São Luís/MA'),
    ('Supermercado Teresina', -7.235117, -39.267266, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Teresina/PI'),
    ('Supermercado Macaé', -7.163770, -39.336109, 'Juazeiro do Norte/CE (localização fictícia) — preços da cesta DIEESE de Macaé/RJ');

-- 3. Produtos: os itens da cesta básica.
INSERT INTO produtos (nome, categoria)
VALUES
    ('Carne bovina', 'Açougue'),
    ('Leite integral', 'Laticínios'),
    ('Feijão', 'Mercearia'),
    ('Arroz', 'Mercearia'),
    ('Farinha', 'Mercearia'),
    ('Batata', 'Hortifruti'),
    ('Tomate', 'Hortifruti'),
    ('Pão francês', 'Padaria'),
    ('Café em pó', 'Mercearia'),
    ('Banana (dúzia)', 'Hortifruti'),
    ('Açúcar', 'Mercearia'),
    ('Óleo de soja (900 ml)', 'Mercearia'),
    ('Manteiga', 'Laticínios');

-- 4. Marcas fictícias: duas por produto.
INSERT INTO marcas (produto_id, nome)
SELECT p.id, d.marca
  FROM (
      VALUES
          ('Carne bovina', 'Boi Nobre'),
          ('Carne bovina', 'Corte Bom'),
          ('Leite integral', 'Vale Verde'),
          ('Leite integral', 'Leiteria Serrana'),
          ('Feijão', 'Grão de Ouro'),
          ('Feijão', 'Sertão Forte'),
          ('Arroz', 'Campo Dourado'),
          ('Arroz', 'Arrozal'),
          ('Farinha', 'Moinho Real'),
          ('Farinha', 'Farinheira do Vale'),
          ('Batata', 'Horta Viva'),
          ('Batata', 'Terra Boa'),
          ('Tomate', 'Horta Viva'),
          ('Tomate', 'Terra Boa'),
          ('Pão francês', 'Trigal'),
          ('Pão francês', 'Forno Bom'),
          ('Café em pó', 'Serra Alta'),
          ('Café em pó', 'Grão Torrado'),
          ('Banana (dúzia)', 'Horta Viva'),
          ('Banana (dúzia)', 'Terra Boa'),
          ('Açúcar', 'Doce Lar'),
          ('Açúcar', 'Canavial'),
          ('Óleo de soja (900 ml)', 'Soja Pura'),
          ('Óleo de soja (900 ml)', 'Óleo Bom'),
          ('Manteiga', 'Vale Verde'),
          ('Manteiga', 'Leiteria Serrana')
  ) AS d(produto, marca)
  JOIN produtos p ON p.nome = d.produto;

-- 5. Preços: 670 snapshots, dois por célula preenchida do CSV.
WITH dados (mercado_nome, produto_nome, marca_nome, preco, unidade) AS (
    VALUES
        ('Supermercado Brasília', 'Carne bovina', 'Boi Nobre', 48.93::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Carne bovina', 'Corte Bom', 41.69::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Leite integral', 'Vale Verde', 7.31::numeric(10,2), 'L'),
        ('Supermercado Brasília', 'Leite integral', 'Leiteria Serrana', 6.23::numeric(10,2), 'L'),
        ('Supermercado Brasília', 'Feijão', 'Grão de Ouro', 9.70::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Feijão', 'Sertão Forte', 8.26::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Arroz', 'Campo Dourado', 5.11::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Arroz', 'Arrozal', 4.35::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Farinha', 'Moinho Real', 5.02::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Farinha', 'Farinheira do Vale', 4.28::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Batata', 'Horta Viva', 4.78::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Batata', 'Terra Boa', 4.08::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Tomate', 'Horta Viva', 6.84::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Tomate', 'Terra Boa', 5.82::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Pão francês', 'Trigal', 20.41::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Pão francês', 'Forno Bom', 17.39::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Café em pó', 'Serra Alta', 53.03::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Café em pó', 'Grão Torrado', 45.17::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Banana (dúzia)', 'Horta Viva', 9.46::numeric(10,2), 'un'),
        ('Supermercado Brasília', 'Banana (dúzia)', 'Terra Boa', 8.06::numeric(10,2), 'un'),
        ('Supermercado Brasília', 'Açúcar', 'Doce Lar', 3.19::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Açúcar', 'Canavial', 2.71::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Óleo de soja (900 ml)', 'Soja Pura', 7.84::numeric(10,2), 'un'),
        ('Supermercado Brasília', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.68::numeric(10,2), 'un'),
        ('Supermercado Brasília', 'Manteiga', 'Vale Verde', 60.35::numeric(10,2), 'kg'),
        ('Supermercado Brasília', 'Manteiga', 'Leiteria Serrana', 51.41::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Carne bovina', 'Boi Nobre', 52.91::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Carne bovina', 'Corte Bom', 45.07::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Leite integral', 'Vale Verde', 6.57::numeric(10,2), 'L'),
        ('Supermercado Campo Grande', 'Leite integral', 'Leiteria Serrana', 5.59::numeric(10,2), 'L'),
        ('Supermercado Campo Grande', 'Feijão', 'Grão de Ouro', 9.67::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Feijão', 'Sertão Forte', 8.23::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Arroz', 'Campo Dourado', 4.53::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Arroz', 'Arrozal', 3.85::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Farinha', 'Moinho Real', 4.70::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Farinha', 'Farinheira do Vale', 4.00::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Batata', 'Horta Viva', 5.19::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Batata', 'Terra Boa', 4.43::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Tomate', 'Horta Viva', 6.51::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Tomate', 'Terra Boa', 5.55::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Pão francês', 'Trigal', 19.62::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Pão francês', 'Forno Bom', 16.72::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Café em pó', 'Serra Alta', 53.51::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Café em pó', 'Grão Torrado', 45.59::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Banana (dúzia)', 'Horta Viva', 12.78::numeric(10,2), 'un'),
        ('Supermercado Campo Grande', 'Banana (dúzia)', 'Terra Boa', 10.88::numeric(10,2), 'un'),
        ('Supermercado Campo Grande', 'Açúcar', 'Doce Lar', 3.08::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Açúcar', 'Canavial', 2.62::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Óleo de soja (900 ml)', 'Soja Pura', 7.64::numeric(10,2), 'un'),
        ('Supermercado Campo Grande', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.50::numeric(10,2), 'un'),
        ('Supermercado Campo Grande', 'Manteiga', 'Vale Verde', 70.82::numeric(10,2), 'kg'),
        ('Supermercado Campo Grande', 'Manteiga', 'Leiteria Serrana', 60.32::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Carne bovina', 'Boi Nobre', 49.64::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Carne bovina', 'Corte Bom', 42.28::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Leite integral', 'Vale Verde', 7.60::numeric(10,2), 'L'),
        ('Supermercado Cuiabá', 'Leite integral', 'Leiteria Serrana', 6.48::numeric(10,2), 'L'),
        ('Supermercado Cuiabá', 'Feijão', 'Grão de Ouro', 9.13::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Feijão', 'Sertão Forte', 7.77::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Arroz', 'Campo Dourado', 4.44::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Arroz', 'Arrozal', 3.78::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Farinha', 'Moinho Real', 4.72::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Farinha', 'Farinheira do Vale', 4.02::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Batata', 'Horta Viva', 7.42::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Batata', 'Terra Boa', 6.32::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Tomate', 'Horta Viva', 8.83::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Tomate', 'Terra Boa', 7.53::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Pão francês', 'Trigal', 23.33::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Pão francês', 'Forno Bom', 19.87::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Café em pó', 'Serra Alta', 62.10::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Café em pó', 'Grão Torrado', 52.90::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Banana (dúzia)', 'Horta Viva', 13.99::numeric(10,2), 'un'),
        ('Supermercado Cuiabá', 'Banana (dúzia)', 'Terra Boa', 11.91::numeric(10,2), 'un'),
        ('Supermercado Cuiabá', 'Açúcar', 'Doce Lar', 3.06::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Açúcar', 'Canavial', 2.60::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Óleo de soja (900 ml)', 'Soja Pura', 8.14::numeric(10,2), 'un'),
        ('Supermercado Cuiabá', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.94::numeric(10,2), 'un'),
        ('Supermercado Cuiabá', 'Manteiga', 'Vale Verde', 64.65::numeric(10,2), 'kg'),
        ('Supermercado Cuiabá', 'Manteiga', 'Leiteria Serrana', 55.07::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Carne bovina', 'Boi Nobre', 49.65::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Carne bovina', 'Corte Bom', 42.29::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Leite integral', 'Vale Verde', 7.47::numeric(10,2), 'L'),
        ('Supermercado Goiânia', 'Leite integral', 'Leiteria Serrana', 6.37::numeric(10,2), 'L'),
        ('Supermercado Goiânia', 'Feijão', 'Grão de Ouro', 11.86::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Feijão', 'Sertão Forte', 10.10::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Arroz', 'Campo Dourado', 4.97::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Arroz', 'Arrozal', 4.23::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Farinha', 'Moinho Real', 5.35::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Farinha', 'Farinheira do Vale', 4.55::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Batata', 'Horta Viva', 5.86::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Batata', 'Terra Boa', 5.00::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Tomate', 'Horta Viva', 7.13::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Tomate', 'Terra Boa', 6.07::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Pão francês', 'Trigal', 21.07::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Pão francês', 'Forno Bom', 17.95::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Café em pó', 'Serra Alta', 74.04::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Café em pó', 'Grão Torrado', 63.08::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Banana (dúzia)', 'Horta Viva', 9.42::numeric(10,2), 'un'),
        ('Supermercado Goiânia', 'Banana (dúzia)', 'Terra Boa', 8.02::numeric(10,2), 'un'),
        ('Supermercado Goiânia', 'Açúcar', 'Doce Lar', 3.49::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Açúcar', 'Canavial', 2.97::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Óleo de soja (900 ml)', 'Soja Pura', 8.02::numeric(10,2), 'un'),
        ('Supermercado Goiânia', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.84::numeric(10,2), 'un'),
        ('Supermercado Goiânia', 'Manteiga', 'Vale Verde', 60.24::numeric(10,2), 'kg'),
        ('Supermercado Goiânia', 'Manteiga', 'Leiteria Serrana', 51.32::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Carne bovina', 'Boi Nobre', 52.19::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Carne bovina', 'Corte Bom', 44.45::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Leite integral', 'Vale Verde', 7.13::numeric(10,2), 'L'),
        ('Supermercado Belo Horizonte', 'Leite integral', 'Leiteria Serrana', 6.07::numeric(10,2), 'L'),
        ('Supermercado Belo Horizonte', 'Feijão', 'Grão de Ouro', 10.03::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Feijão', 'Sertão Forte', 8.55::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Arroz', 'Campo Dourado', 4.92::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Arroz', 'Arrozal', 4.20::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Farinha', 'Moinho Real', 4.78::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Farinha', 'Farinheira do Vale', 4.08::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Batata', 'Horta Viva', 5.41::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Batata', 'Terra Boa', 4.61::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Tomate', 'Horta Viva', 7.85::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Tomate', 'Terra Boa', 6.69::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Pão francês', 'Trigal', 20.91::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Pão francês', 'Forno Bom', 17.81::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Café em pó', 'Serra Alta', 52.27::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Café em pó', 'Grão Torrado', 44.53::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Banana (dúzia)', 'Horta Viva', 9.61::numeric(10,2), 'un'),
        ('Supermercado Belo Horizonte', 'Banana (dúzia)', 'Terra Boa', 8.19::numeric(10,2), 'un'),
        ('Supermercado Belo Horizonte', 'Açúcar', 'Doce Lar', 3.10::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Açúcar', 'Canavial', 2.64::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Óleo de soja (900 ml)', 'Soja Pura', 7.99::numeric(10,2), 'un'),
        ('Supermercado Belo Horizonte', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.81::numeric(10,2), 'un'),
        ('Supermercado Belo Horizonte', 'Manteiga', 'Vale Verde', 49.73::numeric(10,2), 'kg'),
        ('Supermercado Belo Horizonte', 'Manteiga', 'Leiteria Serrana', 42.37::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Carne bovina', 'Boi Nobre', 57.32::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Carne bovina', 'Corte Bom', 48.82::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Leite integral', 'Vale Verde', 8.13::numeric(10,2), 'L'),
        ('Supermercado Rio de Janeiro', 'Leite integral', 'Leiteria Serrana', 6.93::numeric(10,2), 'L'),
        ('Supermercado Rio de Janeiro', 'Feijão', 'Grão de Ouro', 7.20::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Feijão', 'Sertão Forte', 6.14::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Arroz', 'Campo Dourado', 6.03::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Arroz', 'Arrozal', 5.13::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Farinha', 'Moinho Real', 5.35::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Farinha', 'Farinheira do Vale', 4.55::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Batata', 'Horta Viva', 5.98::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Batata', 'Terra Boa', 5.10::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Tomate', 'Horta Viva', 8.58::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Tomate', 'Terra Boa', 7.30::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Pão francês', 'Trigal', 22.74::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Pão francês', 'Forno Bom', 19.38::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Café em pó', 'Serra Alta', 59.73::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Café em pó', 'Grão Torrado', 50.89::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Banana (dúzia)', 'Horta Viva', 12.40::numeric(10,2), 'un'),
        ('Supermercado Rio de Janeiro', 'Banana (dúzia)', 'Terra Boa', 10.56::numeric(10,2), 'un'),
        ('Supermercado Rio de Janeiro', 'Açúcar', 'Doce Lar', 3.81::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Açúcar', 'Canavial', 3.25::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Óleo de soja (900 ml)', 'Soja Pura', 8.24::numeric(10,2), 'un'),
        ('Supermercado Rio de Janeiro', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.02::numeric(10,2), 'un'),
        ('Supermercado Rio de Janeiro', 'Manteiga', 'Vale Verde', 77.08::numeric(10,2), 'kg'),
        ('Supermercado Rio de Janeiro', 'Manteiga', 'Leiteria Serrana', 65.66::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Carne bovina', 'Boi Nobre', 59.86::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Carne bovina', 'Corte Bom', 51.00::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Leite integral', 'Vale Verde', 7.81::numeric(10,2), 'L'),
        ('Supermercado São Paulo', 'Leite integral', 'Leiteria Serrana', 6.65::numeric(10,2), 'L'),
        ('Supermercado São Paulo', 'Feijão', 'Grão de Ouro', 10.52::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Feijão', 'Sertão Forte', 8.96::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Arroz', 'Campo Dourado', 4.92::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Arroz', 'Arrozal', 4.20::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Farinha', 'Moinho Real', 5.65::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Farinha', 'Farinheira do Vale', 4.81::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Batata', 'Horta Viva', 8.37::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Batata', 'Terra Boa', 7.13::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Tomate', 'Horta Viva', 10.08::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Tomate', 'Terra Boa', 8.58::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Pão francês', 'Trigal', 21.55::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Pão francês', 'Forno Bom', 18.35::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Café em pó', 'Serra Alta', 63.12::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Café em pó', 'Grão Torrado', 53.76::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Banana (dúzia)', 'Horta Viva', 13.32::numeric(10,2), 'un'),
        ('Supermercado São Paulo', 'Banana (dúzia)', 'Terra Boa', 11.34::numeric(10,2), 'un'),
        ('Supermercado São Paulo', 'Açúcar', 'Doce Lar', 3.90::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Açúcar', 'Canavial', 3.32::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Óleo de soja (900 ml)', 'Soja Pura', 8.41::numeric(10,2), 'un'),
        ('Supermercado São Paulo', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.17::numeric(10,2), 'un'),
        ('Supermercado São Paulo', 'Manteiga', 'Vale Verde', 75.01::numeric(10,2), 'kg'),
        ('Supermercado São Paulo', 'Manteiga', 'Leiteria Serrana', 63.89::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Carne bovina', 'Boi Nobre', 54.13::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Carne bovina', 'Corte Bom', 46.11::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Leite integral', 'Vale Verde', 7.26::numeric(10,2), 'L'),
        ('Supermercado Vitória', 'Leite integral', 'Leiteria Serrana', 6.18::numeric(10,2), 'L'),
        ('Supermercado Vitória', 'Feijão', 'Grão de Ouro', 7.82::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Feijão', 'Sertão Forte', 6.66::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Arroz', 'Campo Dourado', 4.11::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Arroz', 'Arrozal', 3.51::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Farinha', 'Moinho Real', 4.56::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Farinha', 'Farinheira do Vale', 3.88::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Batata', 'Horta Viva', 6.67::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Batata', 'Terra Boa', 5.69::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Tomate', 'Horta Viva', 8.54::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Tomate', 'Terra Boa', 7.28::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Pão francês', 'Trigal', 22.17::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Pão francês', 'Forno Bom', 18.89::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Café em pó', 'Serra Alta', 49.26::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Café em pó', 'Grão Torrado', 41.96::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Banana (dúzia)', 'Horta Viva', 9.43::numeric(10,2), 'un'),
        ('Supermercado Vitória', 'Banana (dúzia)', 'Terra Boa', 8.03::numeric(10,2), 'un'),
        ('Supermercado Vitória', 'Açúcar', 'Doce Lar', 3.03::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Açúcar', 'Canavial', 2.59::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Óleo de soja (900 ml)', 'Soja Pura', 8.40::numeric(10,2), 'un'),
        ('Supermercado Vitória', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.16::numeric(10,2), 'un'),
        ('Supermercado Vitória', 'Manteiga', 'Vale Verde', 69.16::numeric(10,2), 'kg'),
        ('Supermercado Vitória', 'Manteiga', 'Leiteria Serrana', 58.92::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Carne bovina', 'Boi Nobre', 57.94::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Carne bovina', 'Corte Bom', 49.36::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Leite integral', 'Vale Verde', 7.17::numeric(10,2), 'L'),
        ('Supermercado Curitiba', 'Leite integral', 'Leiteria Serrana', 6.11::numeric(10,2), 'L'),
        ('Supermercado Curitiba', 'Feijão', 'Grão de Ouro', 6.85::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Feijão', 'Sertão Forte', 5.83::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Arroz', 'Campo Dourado', 4.31::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Arroz', 'Arrozal', 3.67::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Farinha', 'Moinho Real', 4.59::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Farinha', 'Farinheira do Vale', 3.91::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Batata', 'Horta Viva', 5.16::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Batata', 'Terra Boa', 4.40::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Tomate', 'Horta Viva', 8.00::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Tomate', 'Terra Boa', 6.82::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Pão francês', 'Trigal', 17.98::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Pão francês', 'Forno Bom', 15.32::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Café em pó', 'Serra Alta', 52.12::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Café em pó', 'Grão Torrado', 44.40::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Banana (dúzia)', 'Horta Viva', 9.04::numeric(10,2), 'un'),
        ('Supermercado Curitiba', 'Banana (dúzia)', 'Terra Boa', 7.70::numeric(10,2), 'un'),
        ('Supermercado Curitiba', 'Açúcar', 'Doce Lar', 4.19::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Açúcar', 'Canavial', 3.57::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Óleo de soja (900 ml)', 'Soja Pura', 7.88::numeric(10,2), 'un'),
        ('Supermercado Curitiba', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.72::numeric(10,2), 'un'),
        ('Supermercado Curitiba', 'Manteiga', 'Vale Verde', 58.59::numeric(10,2), 'kg'),
        ('Supermercado Curitiba', 'Manteiga', 'Leiteria Serrana', 49.91::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Carne bovina', 'Boi Nobre', 59.04::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Carne bovina', 'Corte Bom', 50.30::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Leite integral', 'Vale Verde', 6.85::numeric(10,2), 'L'),
        ('Supermercado Florianópolis', 'Leite integral', 'Leiteria Serrana', 5.83::numeric(10,2), 'L'),
        ('Supermercado Florianópolis', 'Feijão', 'Grão de Ouro', 8.02::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Feijão', 'Sertão Forte', 6.84::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Arroz', 'Campo Dourado', 5.52::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Arroz', 'Arrozal', 4.70::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Farinha', 'Moinho Real', 4.70::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Farinha', 'Farinheira do Vale', 4.00::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Batata', 'Horta Viva', 5.89::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Batata', 'Terra Boa', 5.01::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Tomate', 'Horta Viva', 8.02::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Tomate', 'Terra Boa', 6.84::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Pão francês', 'Trigal', 19.86::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Pão francês', 'Forno Bom', 16.92::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Café em pó', 'Serra Alta', 60.69::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Café em pó', 'Grão Torrado', 51.69::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Banana (dúzia)', 'Horta Viva', 10.55::numeric(10,2), 'un'),
        ('Supermercado Florianópolis', 'Banana (dúzia)', 'Terra Boa', 8.99::numeric(10,2), 'un'),
        ('Supermercado Florianópolis', 'Açúcar', 'Doce Lar', 4.51::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Açúcar', 'Canavial', 3.85::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Óleo de soja (900 ml)', 'Soja Pura', 8.35::numeric(10,2), 'un'),
        ('Supermercado Florianópolis', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.11::numeric(10,2), 'un'),
        ('Supermercado Florianópolis', 'Manteiga', 'Vale Verde', 69.85::numeric(10,2), 'kg'),
        ('Supermercado Florianópolis', 'Manteiga', 'Leiteria Serrana', 59.51::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Carne bovina', 'Boi Nobre', 58.94::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Carne bovina', 'Corte Bom', 50.20::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Leite integral', 'Vale Verde', 6.15::numeric(10,2), 'L'),
        ('Supermercado Porto Alegre', 'Leite integral', 'Leiteria Serrana', 5.23::numeric(10,2), 'L'),
        ('Supermercado Porto Alegre', 'Feijão', 'Grão de Ouro', 7.44::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Feijão', 'Sertão Forte', 6.34::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Arroz', 'Campo Dourado', 4.83::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Arroz', 'Arrozal', 4.11::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Farinha', 'Moinho Real', 4.34::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Farinha', 'Farinheira do Vale', 3.70::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Batata', 'Horta Viva', 5.86::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Batata', 'Terra Boa', 5.00::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Tomate', 'Horta Viva', 8.46::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Tomate', 'Terra Boa', 7.20::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Pão francês', 'Trigal', 17.42::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Pão francês', 'Forno Bom', 14.84::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Café em pó', 'Serra Alta', 60.11::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Café em pó', 'Grão Torrado', 51.21::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Banana (dúzia)', 'Horta Viva', 11.58::numeric(10,2), 'un'),
        ('Supermercado Porto Alegre', 'Banana (dúzia)', 'Terra Boa', 9.86::numeric(10,2), 'un'),
        ('Supermercado Porto Alegre', 'Açúcar', 'Doce Lar', 4.28::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Açúcar', 'Canavial', 3.64::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Óleo de soja (900 ml)', 'Soja Pura', 8.48::numeric(10,2), 'un'),
        ('Supermercado Porto Alegre', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.22::numeric(10,2), 'un'),
        ('Supermercado Porto Alegre', 'Manteiga', 'Vale Verde', 73.61::numeric(10,2), 'kg'),
        ('Supermercado Porto Alegre', 'Manteiga', 'Leiteria Serrana', 62.71::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Carne bovina', 'Boi Nobre', 50.16::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Carne bovina', 'Corte Bom', 42.72::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Leite integral', 'Vale Verde', 8.87::numeric(10,2), 'L'),
        ('Supermercado Belém', 'Leite integral', 'Leiteria Serrana', 7.55::numeric(10,2), 'L'),
        ('Supermercado Belém', 'Feijão', 'Grão de Ouro', 9.35::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Feijão', 'Sertão Forte', 7.97::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Arroz', 'Campo Dourado', 5.35::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Arroz', 'Arrozal', 4.55::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Farinha', 'Moinho Real', 8.87::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Farinha', 'Farinheira do Vale', 7.55::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Tomate', 'Horta Viva', 8.72::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Tomate', 'Terra Boa', 7.42::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Pão francês', 'Trigal', 18.37::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Pão francês', 'Forno Bom', 15.65::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Café em pó', 'Serra Alta', 66.64::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Café em pó', 'Grão Torrado', 56.76::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Banana (dúzia)', 'Horta Viva', 12.36::numeric(10,2), 'un'),
        ('Supermercado Belém', 'Banana (dúzia)', 'Terra Boa', 10.52::numeric(10,2), 'un'),
        ('Supermercado Belém', 'Açúcar', 'Doce Lar', 3.76::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Açúcar', 'Canavial', 3.20::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Óleo de soja (900 ml)', 'Soja Pura', 9.13::numeric(10,2), 'un'),
        ('Supermercado Belém', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.77::numeric(10,2), 'un'),
        ('Supermercado Belém', 'Manteiga', 'Vale Verde', 68.19::numeric(10,2), 'kg'),
        ('Supermercado Belém', 'Manteiga', 'Leiteria Serrana', 58.09::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Carne bovina', 'Boi Nobre', 50.25::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Carne bovina', 'Corte Bom', 42.81::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Leite integral', 'Vale Verde', 9.00::numeric(10,2), 'L'),
        ('Supermercado Boa Vista', 'Leite integral', 'Leiteria Serrana', 7.66::numeric(10,2), 'L'),
        ('Supermercado Boa Vista', 'Feijão', 'Grão de Ouro', 10.28::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Feijão', 'Sertão Forte', 8.76::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Arroz', 'Campo Dourado', 4.67::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Arroz', 'Arrozal', 3.97::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Farinha', 'Moinho Real', 9.89::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Farinha', 'Farinheira do Vale', 8.43::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Tomate', 'Horta Viva', 10.50::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Tomate', 'Terra Boa', 8.94::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Pão francês', 'Trigal', 11.86::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Pão francês', 'Forno Bom', 10.10::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Café em pó', 'Serra Alta', 73.15::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Café em pó', 'Grão Torrado', 62.31::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Banana (dúzia)', 'Horta Viva', 11.88::numeric(10,2), 'un'),
        ('Supermercado Boa Vista', 'Banana (dúzia)', 'Terra Boa', 10.12::numeric(10,2), 'un'),
        ('Supermercado Boa Vista', 'Açúcar', 'Doce Lar', 3.83::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Açúcar', 'Canavial', 3.27::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Óleo de soja (900 ml)', 'Soja Pura', 7.86::numeric(10,2), 'un'),
        ('Supermercado Boa Vista', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.70::numeric(10,2), 'un'),
        ('Supermercado Boa Vista', 'Manteiga', 'Vale Verde', 71.32::numeric(10,2), 'kg'),
        ('Supermercado Boa Vista', 'Manteiga', 'Leiteria Serrana', 60.76::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Carne bovina', 'Boi Nobre', 45.64::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Carne bovina', 'Corte Bom', 38.88::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Leite integral', 'Vale Verde', 8.48::numeric(10,2), 'L'),
        ('Supermercado Macapá', 'Leite integral', 'Leiteria Serrana', 7.22::numeric(10,2), 'L'),
        ('Supermercado Macapá', 'Feijão', 'Grão de Ouro', 9.96::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Feijão', 'Sertão Forte', 8.48::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Arroz', 'Campo Dourado', 6.10::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Arroz', 'Arrozal', 5.20::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Farinha', 'Moinho Real', 8.48::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Farinha', 'Farinheira do Vale', 7.22::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Tomate', 'Horta Viva', 11.01::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Tomate', 'Terra Boa', 9.37::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Pão francês', 'Trigal', 17.40::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Pão francês', 'Forno Bom', 14.82::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Café em pó', 'Serra Alta', 71.53::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Café em pó', 'Grão Torrado', 60.93::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Banana (dúzia)', 'Horta Viva', 10.58::numeric(10,2), 'un'),
        ('Supermercado Macapá', 'Banana (dúzia)', 'Terra Boa', 9.02::numeric(10,2), 'un'),
        ('Supermercado Macapá', 'Açúcar', 'Doce Lar', 4.60::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Açúcar', 'Canavial', 3.92::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Óleo de soja (900 ml)', 'Soja Pura', 8.91::numeric(10,2), 'un'),
        ('Supermercado Macapá', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.59::numeric(10,2), 'un'),
        ('Supermercado Macapá', 'Manteiga', 'Vale Verde', 67.23::numeric(10,2), 'kg'),
        ('Supermercado Macapá', 'Manteiga', 'Leiteria Serrana', 57.27::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Carne bovina', 'Boi Nobre', 51.31::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Carne bovina', 'Corte Bom', 43.71::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Leite integral', 'Vale Verde', 8.21::numeric(10,2), 'L'),
        ('Supermercado Manaus', 'Leite integral', 'Leiteria Serrana', 6.99::numeric(10,2), 'L'),
        ('Supermercado Manaus', 'Feijão', 'Grão de Ouro', 9.64::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Feijão', 'Sertão Forte', 8.22::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Arroz', 'Campo Dourado', 5.13::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Arroz', 'Arrozal', 4.37::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Farinha', 'Moinho Real', 6.04::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Farinha', 'Farinheira do Vale', 5.14::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Tomate', 'Horta Viva', 8.12::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Tomate', 'Terra Boa', 6.92::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Pão francês', 'Trigal', 15.79::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Pão francês', 'Forno Bom', 13.45::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Café em pó', 'Serra Alta', 68.15::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Café em pó', 'Grão Torrado', 58.05::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Banana (dúzia)', 'Horta Viva', 10.99::numeric(10,2), 'un'),
        ('Supermercado Manaus', 'Banana (dúzia)', 'Terra Boa', 9.37::numeric(10,2), 'un'),
        ('Supermercado Manaus', 'Açúcar', 'Doce Lar', 3.25::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Açúcar', 'Canavial', 2.77::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Óleo de soja (900 ml)', 'Soja Pura', 8.52::numeric(10,2), 'un'),
        ('Supermercado Manaus', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.26::numeric(10,2), 'un'),
        ('Supermercado Manaus', 'Manteiga', 'Vale Verde', 61.05::numeric(10,2), 'kg'),
        ('Supermercado Manaus', 'Manteiga', 'Leiteria Serrana', 52.01::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Carne bovina', 'Boi Nobre', 51.97::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Carne bovina', 'Corte Bom', 44.27::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Leite integral', 'Vale Verde', 7.44::numeric(10,2), 'L'),
        ('Supermercado Palmas', 'Leite integral', 'Leiteria Serrana', 6.34::numeric(10,2), 'L'),
        ('Supermercado Palmas', 'Feijão', 'Grão de Ouro', 12.70::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Feijão', 'Sertão Forte', 10.82::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Arroz', 'Campo Dourado', 6.50::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Arroz', 'Arrozal', 5.54::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Farinha', 'Moinho Real', 9.93::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Farinha', 'Farinheira do Vale', 8.45::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Tomate', 'Horta Viva', 6.77::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Tomate', 'Terra Boa', 5.77::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Pão francês', 'Trigal', 20.66::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Pão francês', 'Forno Bom', 17.60::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Café em pó', 'Serra Alta', 71.50::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Café em pó', 'Grão Torrado', 60.90::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Banana (dúzia)', 'Horta Viva', 10.10::numeric(10,2), 'un'),
        ('Supermercado Palmas', 'Banana (dúzia)', 'Terra Boa', 8.60::numeric(10,2), 'un'),
        ('Supermercado Palmas', 'Açúcar', 'Doce Lar', 4.37::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Açúcar', 'Canavial', 3.73::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Óleo de soja (900 ml)', 'Soja Pura', 9.48::numeric(10,2), 'un'),
        ('Supermercado Palmas', 'Óleo de soja (900 ml)', 'Óleo Bom', 8.08::numeric(10,2), 'un'),
        ('Supermercado Palmas', 'Manteiga', 'Vale Verde', 82.89::numeric(10,2), 'kg'),
        ('Supermercado Palmas', 'Manteiga', 'Leiteria Serrana', 70.61::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Carne bovina', 'Boi Nobre', 43.12::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Carne bovina', 'Corte Bom', 36.74::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Leite integral', 'Vale Verde', 7.25::numeric(10,2), 'L'),
        ('Supermercado Porto Velho', 'Leite integral', 'Leiteria Serrana', 6.17::numeric(10,2), 'L'),
        ('Supermercado Porto Velho', 'Feijão', 'Grão de Ouro', 9.15::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Feijão', 'Sertão Forte', 7.79::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Arroz', 'Campo Dourado', 4.97::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Arroz', 'Arrozal', 4.23::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Farinha', 'Moinho Real', 7.02::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Farinha', 'Farinheira do Vale', 5.98::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Tomate', 'Horta Viva', 9.74::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Tomate', 'Terra Boa', 8.30::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Pão francês', 'Trigal', 16.91::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Pão francês', 'Forno Bom', 14.41::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Café em pó', 'Serra Alta', 70.61::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Café em pó', 'Grão Torrado', 60.15::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Banana (dúzia)', 'Horta Viva', 14.04::numeric(10,2), 'un'),
        ('Supermercado Porto Velho', 'Banana (dúzia)', 'Terra Boa', 11.96::numeric(10,2), 'un'),
        ('Supermercado Porto Velho', 'Açúcar', 'Doce Lar', 3.00::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Açúcar', 'Canavial', 2.56::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Óleo de soja (900 ml)', 'Soja Pura', 8.14::numeric(10,2), 'un'),
        ('Supermercado Porto Velho', 'Óleo de soja (900 ml)', 'Óleo Bom', 6.94::numeric(10,2), 'un'),
        ('Supermercado Porto Velho', 'Manteiga', 'Vale Verde', 51.07::numeric(10,2), 'kg'),
        ('Supermercado Porto Velho', 'Manteiga', 'Leiteria Serrana', 43.51::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Carne bovina', 'Boi Nobre', 42.85::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Carne bovina', 'Corte Bom', 36.51::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Leite integral', 'Vale Verde', 8.23::numeric(10,2), 'L'),
        ('Supermercado Rio Branco', 'Leite integral', 'Leiteria Serrana', 7.01::numeric(10,2), 'L'),
        ('Supermercado Rio Branco', 'Feijão', 'Grão de Ouro', 9.56::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Feijão', 'Sertão Forte', 8.14::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Arroz', 'Campo Dourado', 5.51::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Arroz', 'Arrozal', 4.69::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Farinha', 'Moinho Real', 6.72::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Farinha', 'Farinheira do Vale', 5.72::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Tomate', 'Horta Viva', 9.29::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Tomate', 'Terra Boa', 7.91::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Pão francês', 'Trigal', 15.90::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Pão francês', 'Forno Bom', 13.54::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Café em pó', 'Serra Alta', 64.34::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Café em pó', 'Grão Torrado', 54.80::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Banana (dúzia)', 'Horta Viva', 12.65::numeric(10,2), 'un'),
        ('Supermercado Rio Branco', 'Banana (dúzia)', 'Terra Boa', 10.77::numeric(10,2), 'un'),
        ('Supermercado Rio Branco', 'Açúcar', 'Doce Lar', 3.56::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Açúcar', 'Canavial', 3.04::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Óleo de soja (900 ml)', 'Soja Pura', 8.76::numeric(10,2), 'un'),
        ('Supermercado Rio Branco', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.46::numeric(10,2), 'un'),
        ('Supermercado Rio Branco', 'Manteiga', 'Vale Verde', 62.35::numeric(10,2), 'kg'),
        ('Supermercado Rio Branco', 'Manteiga', 'Leiteria Serrana', 53.11::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Carne bovina', 'Boi Nobre', 47.52::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Carne bovina', 'Corte Bom', 40.48::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Leite integral', 'Vale Verde', 7.32::numeric(10,2), 'L'),
        ('Supermercado Aracaju', 'Leite integral', 'Leiteria Serrana', 6.24::numeric(10,2), 'L'),
        ('Supermercado Aracaju', 'Feijão', 'Grão de Ouro', 10.28::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Feijão', 'Sertão Forte', 8.76::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Arroz', 'Campo Dourado', 5.57::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Arroz', 'Arrozal', 4.75::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Farinha', 'Moinho Real', 7.30::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Farinha', 'Farinheira do Vale', 6.22::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Tomate', 'Horta Viva', 4.35::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Tomate', 'Terra Boa', 3.71::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Pão francês', 'Trigal', 13.41::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Pão francês', 'Forno Bom', 11.43::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Café em pó', 'Serra Alta', 67.33::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Café em pó', 'Grão Torrado', 57.35::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Banana (dúzia)', 'Horta Viva', 8.11::numeric(10,2), 'un'),
        ('Supermercado Aracaju', 'Banana (dúzia)', 'Terra Boa', 6.91::numeric(10,2), 'un'),
        ('Supermercado Aracaju', 'Açúcar', 'Doce Lar', 3.65::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Açúcar', 'Canavial', 3.11::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Óleo de soja (900 ml)', 'Soja Pura', 8.61::numeric(10,2), 'un'),
        ('Supermercado Aracaju', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.33::numeric(10,2), 'un'),
        ('Supermercado Aracaju', 'Manteiga', 'Vale Verde', 49.80::numeric(10,2), 'kg'),
        ('Supermercado Aracaju', 'Manteiga', 'Leiteria Serrana', 42.42::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Carne bovina', 'Boi Nobre', 60.66::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Carne bovina', 'Corte Bom', 51.68::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Leite integral', 'Vale Verde', 7.87::numeric(10,2), 'L'),
        ('Supermercado Fortaleza', 'Leite integral', 'Leiteria Serrana', 6.71::numeric(10,2), 'L'),
        ('Supermercado Fortaleza', 'Feijão', 'Grão de Ouro', 9.91::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Feijão', 'Sertão Forte', 8.45::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Arroz', 'Campo Dourado', 5.49::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Arroz', 'Arrozal', 4.67::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Farinha', 'Moinho Real', 5.70::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Farinha', 'Farinheira do Vale', 4.86::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Tomate', 'Horta Viva', 8.35::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Tomate', 'Terra Boa', 7.11::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Pão francês', 'Trigal', 23.81::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Pão francês', 'Forno Bom', 20.29::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Café em pó', 'Serra Alta', 66.90::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Café em pó', 'Grão Torrado', 56.98::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Banana (dúzia)', 'Horta Viva', 9.57::numeric(10,2), 'un'),
        ('Supermercado Fortaleza', 'Banana (dúzia)', 'Terra Boa', 8.15::numeric(10,2), 'un'),
        ('Supermercado Fortaleza', 'Açúcar', 'Doce Lar', 3.87::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Açúcar', 'Canavial', 3.29::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Óleo de soja (900 ml)', 'Soja Pura', 9.33::numeric(10,2), 'un'),
        ('Supermercado Fortaleza', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.95::numeric(10,2), 'un'),
        ('Supermercado Fortaleza', 'Manteiga', 'Vale Verde', 77.95::numeric(10,2), 'kg'),
        ('Supermercado Fortaleza', 'Manteiga', 'Leiteria Serrana', 66.41::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Carne bovina', 'Boi Nobre', 51.88::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Carne bovina', 'Corte Bom', 44.20::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Leite integral', 'Vale Verde', 8.33::numeric(10,2), 'L'),
        ('Supermercado João Pessoa', 'Leite integral', 'Leiteria Serrana', 7.09::numeric(10,2), 'L'),
        ('Supermercado João Pessoa', 'Feijão', 'Grão de Ouro', 11.17::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Feijão', 'Sertão Forte', 9.51::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Arroz', 'Campo Dourado', 4.94::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Arroz', 'Arrozal', 4.20::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Farinha', 'Moinho Real', 7.64::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Farinha', 'Farinheira do Vale', 6.50::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Tomate', 'Horta Viva', 5.21::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Tomate', 'Terra Boa', 4.43::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Pão francês', 'Trigal', 16.78::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Pão francês', 'Forno Bom', 14.30::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Café em pó', 'Serra Alta', 60.30::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Café em pó', 'Grão Torrado', 51.36::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Banana (dúzia)', 'Horta Viva', 7.95::numeric(10,2), 'un'),
        ('Supermercado João Pessoa', 'Banana (dúzia)', 'Terra Boa', 6.77::numeric(10,2), 'un'),
        ('Supermercado João Pessoa', 'Açúcar', 'Doce Lar', 3.63::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Açúcar', 'Canavial', 3.09::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Óleo de soja (900 ml)', 'Soja Pura', 9.73::numeric(10,2), 'un'),
        ('Supermercado João Pessoa', 'Óleo de soja (900 ml)', 'Óleo Bom', 8.29::numeric(10,2), 'un'),
        ('Supermercado João Pessoa', 'Manteiga', 'Vale Verde', 75.43::numeric(10,2), 'kg'),
        ('Supermercado João Pessoa', 'Manteiga', 'Leiteria Serrana', 64.25::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Carne bovina', 'Boi Nobre', 53.82::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Carne bovina', 'Corte Bom', 45.84::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Leite integral', 'Vale Verde', 7.39::numeric(10,2), 'L'),
        ('Supermercado Maceió', 'Leite integral', 'Leiteria Serrana', 6.29::numeric(10,2), 'L'),
        ('Supermercado Maceió', 'Feijão', 'Grão de Ouro', 10.35::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Feijão', 'Sertão Forte', 8.81::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Arroz', 'Campo Dourado', 5.66::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Arroz', 'Arrozal', 4.82::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Farinha', 'Moinho Real', 6.58::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Farinha', 'Farinheira do Vale', 5.60::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Tomate', 'Horta Viva', 4.78::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Tomate', 'Terra Boa', 4.08::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Pão francês', 'Trigal', 16.06::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Pão francês', 'Forno Bom', 13.68::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Café em pó', 'Serra Alta', 65.08::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Café em pó', 'Grão Torrado', 55.44::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Banana (dúzia)', 'Horta Viva', 8.01::numeric(10,2), 'un'),
        ('Supermercado Maceió', 'Banana (dúzia)', 'Terra Boa', 6.83::numeric(10,2), 'un'),
        ('Supermercado Maceió', 'Açúcar', 'Doce Lar', 3.89::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Açúcar', 'Canavial', 3.31::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Óleo de soja (900 ml)', 'Soja Pura', 9.15::numeric(10,2), 'un'),
        ('Supermercado Maceió', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.79::numeric(10,2), 'un'),
        ('Supermercado Maceió', 'Manteiga', 'Vale Verde', 67.04::numeric(10,2), 'kg'),
        ('Supermercado Maceió', 'Manteiga', 'Leiteria Serrana', 57.10::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Carne bovina', 'Boi Nobre', 51.88::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Carne bovina', 'Corte Bom', 44.20::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Leite integral', 'Vale Verde', 8.18::numeric(10,2), 'L'),
        ('Supermercado Natal', 'Leite integral', 'Leiteria Serrana', 6.96::numeric(10,2), 'L'),
        ('Supermercado Natal', 'Feijão', 'Grão de Ouro', 10.58::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Feijão', 'Sertão Forte', 9.02::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Arroz', 'Campo Dourado', 4.89::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Arroz', 'Arrozal', 4.17::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Farinha', 'Moinho Real', 7.31::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Farinha', 'Farinheira do Vale', 6.23::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Tomate', 'Horta Viva', 5.15::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Tomate', 'Terra Boa', 4.39::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Pão francês', 'Trigal', 16.32::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Pão francês', 'Forno Bom', 13.90::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Café em pó', 'Serra Alta', 65.78::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Café em pó', 'Grão Torrado', 56.04::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Banana (dúzia)', 'Horta Viva', 7.45::numeric(10,2), 'un'),
        ('Supermercado Natal', 'Banana (dúzia)', 'Terra Boa', 6.35::numeric(10,2), 'un'),
        ('Supermercado Natal', 'Açúcar', 'Doce Lar', 3.82::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Açúcar', 'Canavial', 3.26::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Óleo de soja (900 ml)', 'Soja Pura', 9.32::numeric(10,2), 'un'),
        ('Supermercado Natal', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.94::numeric(10,2), 'un'),
        ('Supermercado Natal', 'Manteiga', 'Vale Verde', 69.02::numeric(10,2), 'kg'),
        ('Supermercado Natal', 'Manteiga', 'Leiteria Serrana', 58.80::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Carne bovina', 'Boi Nobre', 49.68::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Carne bovina', 'Corte Bom', 42.32::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Leite integral', 'Vale Verde', 7.43::numeric(10,2), 'L'),
        ('Supermercado Recife', 'Leite integral', 'Leiteria Serrana', 6.33::numeric(10,2), 'L'),
        ('Supermercado Recife', 'Feijão', 'Grão de Ouro', 10.94::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Feijão', 'Sertão Forte', 9.32::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Arroz', 'Campo Dourado', 6.13::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Arroz', 'Arrozal', 5.23::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Farinha', 'Moinho Real', 6.75::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Farinha', 'Farinheira do Vale', 5.75::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Tomate', 'Horta Viva', 5.41::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Tomate', 'Terra Boa', 4.61::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Pão francês', 'Trigal', 15.55::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Pão francês', 'Forno Bom', 13.25::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Café em pó', 'Serra Alta', 64.54::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Café em pó', 'Grão Torrado', 54.98::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Banana (dúzia)', 'Horta Viva', 11.34::numeric(10,2), 'un'),
        ('Supermercado Recife', 'Banana (dúzia)', 'Terra Boa', 9.66::numeric(10,2), 'un'),
        ('Supermercado Recife', 'Açúcar', 'Doce Lar', 4.06::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Açúcar', 'Canavial', 3.46::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Óleo de soja (900 ml)', 'Soja Pura', 9.76::numeric(10,2), 'un'),
        ('Supermercado Recife', 'Óleo de soja (900 ml)', 'Óleo Bom', 8.32::numeric(10,2), 'un'),
        ('Supermercado Recife', 'Manteiga', 'Vale Verde', 66.85::numeric(10,2), 'kg'),
        ('Supermercado Recife', 'Manteiga', 'Leiteria Serrana', 56.95::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Carne bovina', 'Boi Nobre', 48.31::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Carne bovina', 'Corte Bom', 41.15::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Leite integral', 'Vale Verde', 8.61::numeric(10,2), 'L'),
        ('Supermercado Salvador', 'Leite integral', 'Leiteria Serrana', 7.33::numeric(10,2), 'L'),
        ('Supermercado Salvador', 'Feijão', 'Grão de Ouro', 10.84::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Feijão', 'Sertão Forte', 9.24::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Arroz', 'Campo Dourado', 5.81::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Arroz', 'Arrozal', 4.95::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Farinha', 'Moinho Real', 7.75::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Farinha', 'Farinheira do Vale', 6.61::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Tomate', 'Horta Viva', 5.23::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Tomate', 'Terra Boa', 4.45::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Pão francês', 'Trigal', 18.25::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Pão francês', 'Forno Bom', 15.55::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Café em pó', 'Serra Alta', 67.58::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Café em pó', 'Grão Torrado', 57.56::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Banana (dúzia)', 'Horta Viva', 7.86::numeric(10,2), 'un'),
        ('Supermercado Salvador', 'Banana (dúzia)', 'Terra Boa', 6.70::numeric(10,2), 'un'),
        ('Supermercado Salvador', 'Açúcar', 'Doce Lar', 3.90::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Açúcar', 'Canavial', 3.32::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Óleo de soja (900 ml)', 'Soja Pura', 8.87::numeric(10,2), 'un'),
        ('Supermercado Salvador', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.55::numeric(10,2), 'un'),
        ('Supermercado Salvador', 'Manteiga', 'Vale Verde', 60.19::numeric(10,2), 'kg'),
        ('Supermercado Salvador', 'Manteiga', 'Leiteria Serrana', 51.27::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Carne bovina', 'Boi Nobre', 43.86::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Carne bovina', 'Corte Bom', 37.36::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Leite integral', 'Vale Verde', 6.76::numeric(10,2), 'L'),
        ('Supermercado São Luís', 'Leite integral', 'Leiteria Serrana', 5.76::numeric(10,2), 'L'),
        ('Supermercado São Luís', 'Feijão', 'Grão de Ouro', 7.57::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Feijão', 'Sertão Forte', 6.45::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Arroz', 'Campo Dourado', 4.99::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Arroz', 'Arrozal', 4.25::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Farinha', 'Moinho Real', 10.89::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Farinha', 'Farinheira do Vale', 9.27::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Tomate', 'Horta Viva', 8.14::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Tomate', 'Terra Boa', 6.94::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Pão francês', 'Trigal', 20.81::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Pão francês', 'Forno Bom', 17.73::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Café em pó', 'Serra Alta', 66.18::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Café em pó', 'Grão Torrado', 56.38::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Banana (dúzia)', 'Horta Viva', 10.26::numeric(10,2), 'un'),
        ('Supermercado São Luís', 'Banana (dúzia)', 'Terra Boa', 8.74::numeric(10,2), 'un'),
        ('Supermercado São Luís', 'Açúcar', 'Doce Lar', 4.42::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Açúcar', 'Canavial', 3.76::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Óleo de soja (900 ml)', 'Soja Pura', 10.42::numeric(10,2), 'un'),
        ('Supermercado São Luís', 'Óleo de soja (900 ml)', 'Óleo Bom', 8.88::numeric(10,2), 'un'),
        ('Supermercado São Luís', 'Manteiga', 'Vale Verde', 65.39::numeric(10,2), 'kg'),
        ('Supermercado São Luís', 'Manteiga', 'Leiteria Serrana', 55.71::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Carne bovina', 'Boi Nobre', 50.19::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Carne bovina', 'Corte Bom', 42.75::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Leite integral', 'Vale Verde', 7.89::numeric(10,2), 'L'),
        ('Supermercado Teresina', 'Leite integral', 'Leiteria Serrana', 6.73::numeric(10,2), 'L'),
        ('Supermercado Teresina', 'Feijão', 'Grão de Ouro', 10.28::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Feijão', 'Sertão Forte', 8.76::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Arroz', 'Campo Dourado', 5.15::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Arroz', 'Arrozal', 4.39::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Farinha', 'Moinho Real', 8.64::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Farinha', 'Farinheira do Vale', 7.36::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Tomate', 'Horta Viva', 6.66::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Tomate', 'Terra Boa', 5.68::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Pão francês', 'Trigal', 21.55::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Pão francês', 'Forno Bom', 18.35::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Café em pó', 'Serra Alta', 67.67::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Café em pó', 'Grão Torrado', 57.65::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Banana (dúzia)', 'Horta Viva', 10.29::numeric(10,2), 'un'),
        ('Supermercado Teresina', 'Banana (dúzia)', 'Terra Boa', 8.77::numeric(10,2), 'un'),
        ('Supermercado Teresina', 'Açúcar', 'Doce Lar', 4.00::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Açúcar', 'Canavial', 3.40::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Óleo de soja (900 ml)', 'Soja Pura', 9.17::numeric(10,2), 'un'),
        ('Supermercado Teresina', 'Óleo de soja (900 ml)', 'Óleo Bom', 7.81::numeric(10,2), 'un'),
        ('Supermercado Teresina', 'Manteiga', 'Vale Verde', 70.86::numeric(10,2), 'kg'),
        ('Supermercado Teresina', 'Manteiga', 'Leiteria Serrana', 60.36::numeric(10,2), 'kg')
)
INSERT INTO precos (marca_id, mercado_id, preco, unidade, quantidade_disponivel, coletado_em)
SELECT ma.id, me.id, d.preco, d.unidade, 1000, '2026-08-31 12:00:00-03'::timestamptz
  FROM dados d
  JOIN mercados me ON me.nome = d.mercado_nome
  JOIN produtos pr ON pr.nome = d.produto_nome
  JOIN marcas   ma ON ma.produto_id = pr.id AND ma.nome = d.marca_nome;

-- 6. Lista de demonstração: a cesta inteira, com marca livre
--    (marca_id NULL deixa o otimizador escolher qualquer marca).
INSERT INTO listas_compra (usuario_id, nome)
SELECT id, 'Cesta básica do mês' FROM usuarios WHERE email = 'demo@exemplo.com';

INSERT INTO itens_lista (lista_id, produto_id, marca_id, quantidade, unidade)
SELECT l.id, p.id, NULL, d.quantidade, d.unidade
  FROM (
      VALUES
          ('Carne bovina', 2::numeric(12,3), 'kg'),
          ('Leite integral', 6::numeric(12,3), 'L'),
          ('Feijão', 2::numeric(12,3), 'kg'),
          ('Arroz', 5::numeric(12,3), 'kg'),
          ('Farinha', 1::numeric(12,3), 'kg'),
          ('Batata', 1::numeric(12,3), 'kg'),
          ('Tomate', 1::numeric(12,3), 'kg'),
          ('Pão francês', 1::numeric(12,3), 'kg'),
          ('Café em pó', 1::numeric(12,3), 'kg'),
          ('Banana (dúzia)', 1::numeric(12,3), 'un'),
          ('Açúcar', 1::numeric(12,3), 'kg'),
          ('Óleo de soja (900 ml)', 1::numeric(12,3), 'un'),
          ('Manteiga', 1::numeric(12,3), 'kg')
  ) AS d(produto_nome, quantidade, unidade)
  JOIN usuarios      u ON u.email = 'demo@exemplo.com'
  JOIN listas_compra l ON l.usuario_id = u.id AND l.nome = 'Cesta básica do mês'
  JOIN produtos      p ON p.nome = d.produto_nome;
